In [1]:
# Criar um DataFrame df a partir del fichero iris adjunto.

In [19]:
import numpy as np

In [20]:
import pandas as pd

In [21]:
df_iris=pd.read_csv(r'C:\Users\thais\Desktop\Curso Python e Analise de Dados\Datasets+Data+Science+con+Python+-+Pandas\5.12\iris_dataset.csv', delimiter=",",encoding="ISO-8859-1")

In [22]:
df_iris

,longitud_sépalo,anchura_sépalo,longitud_pétalo,anchura_pétalo,clase
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [23]:
# Calcular a area da petala para todos os registros considerando cada petala como uma elipse - area= pi.altura.largura

In [27]:
df_iris["area_petala"]=df_iris.apply(lambda x:x["longitud_pétalo"]*x["anchura_pétalo"]*np.pi,axis=1)

In [28]:
df_iris

,longitud_sépalo,anchura_sépalo,longitud_pétalo,anchura_pétalo,clase,area_petala
0,5.1,3.5,1.4,0.2,Iris-setosa,0.879646
1,4.9,3.0,1.4,0.2,Iris-setosa,0.879646
2,4.7,3.2,1.3,0.2,Iris-setosa,0.816814
3,4.6,3.1,1.5,0.2,Iris-setosa,0.942478
4,5.0,3.6,1.4,0.2,Iris-setosa,0.879646
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,37.573448
146,6.3,2.5,5.0,1.9,Iris-virginica,29.845130
147,6.5,3.0,5.2,2.0,Iris-virginica,32.672564
148,6.2,3.4,5.4,2.3,Iris-virginica,39.018581
149,5.9,3.0,5.1,1.8,Iris-virginica,28.839821

In [4]:
# Qual a mediana da area da petala?

In [29]:
df_iris["area_petala"].median()

17.640042749906687

In [5]:
# Que valor de area eh superado somente pelos 10% das petalas?

In [30]:
df_iris["area_petala"].quantile(0.9)

38.9337577559383

In [6]:
# Existe correlacao entre a longitude e a largura da petala? - usar metodo corr()

In [31]:
df_iris.corr()

,longitud_sépalo,anchura_sépalo,longitud_pétalo,anchura_pétalo,area_petala
longitud_sépalo,1.000000,-0.109369,0.871754,0.817954,0.857326
anchura_sépalo,-0.109369,1.000000,-0.420516,-0.356544,-0.280612
longitud_pétalo,0.871754,-0.420516,1.000000,0.962757,0.958472
anchura_pétalo,0.817954,-0.356544,0.962757,1.000000,0.980229
area_petala,0.857326,-0.280612,0.958472,0.980229,1.000000