In [1]:
# Crear un df a partir del fichero con la informacion de trafico peatonal.

In [5]:
import pandas as pd

In [7]:
df_peatones=pd.read_csv(r'C:\Users\thais\Desktop\Curso Python e Analise de Dados\Datasets+Data+Science+con+Python+-+Pandas\5.16\PEATONES_2020_mod.csv', delimiter=";",encoding="ISO-8859-1")

In [8]:
df_peatones

,FECHA,HORA,IDENTIFICADOR,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD
0,01/01/2020,0:00:00,PERM_PEA02_PM01,497.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
1,01/01/2020,0:15:00,PERM_PEA02_PM01,244.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
2,01/01/2020,0:30:00,PERM_PEA02_PM01,179.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
3,01/01/2020,0:45:00,PERM_PEA02_PM01,174.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
4,01/01/2020,1:00:00,PERM_PEA02_PM01,131.0,1.0,Centro,Calle Fuencarral,22.0,28004.0,Calle peatonal Datos en prueba,"40,4220090","-3,7008917"
...,...,...,...,...,...,...,...,...,...,...,...,...
288750,30/06/2020,22:45:00,PERM_PEA19_PM01,565.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
288751,30/06/2020,23:00:00,PERM_PEA19_PM01,415.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
288752,30/06/2020,23:15:00,PERM_PEA19_PM01,551.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
288753,30/06/2020,23:30:00,PERM_PEA19_PM01,456.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"
288754,30/06/2020,23:45:00,PERM_PEA19_PM01,532.0,1.0,Centro,Calle Bailén,6.0,28013.0,Acera Pares Datos en prueba,"40,417278","-3,713371"

In [2]:
# Calcular el numero promedio de peatones por cada uno de los distritos.

In [11]:
df_peatones.groupby("DISTRITO")["PEATONES"].agg('mean')

DISTRITO
Arganzuela         651.036304
Centro             488.248612
Chamberí           269.302136
Latina              71.679353
Moncloa-Aravaca    360.899778
Name: PEATONES, dtype: float64

In [3]:
# Obtener el minimo y el promedio de peatones en cada distrito en cada uno de los dias ("FECHA").

In [17]:
df_peatones.groupby(["FECHA","DISTRITO"])['PEATONES'].agg(['min','mean'])

                             min        mean
FECHA      DISTRITO
01/01/2020 Arganzuela       19.0  589.885417
           Centro           10.0  416.541040
01/02/2020 Arganzuela       34.0  579.602094
           Centro            7.0  459.156725
           Chamberí          3.0  313.614583
...                          ...         ...
31/05/2020 Arganzuela       65.0  667.390625
           Centro           11.0  476.013021
           Chamberí         29.0  315.463542
           Latina            6.0   61.031250
           Moncloa-Aravaca  62.0  447.739583

[860 rows x 2 columns]

In [4]:
# Calcular cual ha sido el trafico de peatones maximo total considerando que hay que anadir un 10% de factor de crecimiento por transeuntes motorizados (usar func lambda).

In [18]:
df_peatones.groupby(["FECHA","DISTRITO"])["PEATONES"].agg(['max',lambda x:x.max()*1.1])

                               max  <lambda_0>
FECHA      DISTRITO
01/01/2020 Arganzuela       1577.0      1734.7
           Centro           1434.0      1577.4
01/02/2020 Arganzuela       1809.0      1989.9
           Centro           1477.0      1624.7
           Chamberí         1059.0      1164.9
...                            ...         ...
31/05/2020 Arganzuela       1659.0      1824.9
           Centro           1487.0      1635.7
           Chamberí          897.0       986.7
           Latina            122.0       134.2
           Moncloa-Aravaca   786.0       864.6

[860 rows x 2 columns]